/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePurchaseOrderArgs } from "./CreatePurchaseOrderArgs";
import { UpdatePurchaseOrderArgs } from "./UpdatePurchaseOrderArgs";
import { DeletePurchaseOrderArgs } from "./DeletePurchaseOrderArgs";
import { PurchaseOrderFindManyArgs } from "./PurchaseOrderFindManyArgs";
import { PurchaseOrderFindUniqueArgs } from "./PurchaseOrderFindUniqueArgs";
import { PurchaseOrder } from "./PurchaseOrder";
import { PurchaseOrderItemFindManyArgs } from "../../purchaseOrderItem/base/PurchaseOrderItemFindManyArgs";
import { PurchaseOrderItem } from "../../purchaseOrderItem/base/PurchaseOrderItem";
import { Vendor } from "../../vendor/base/Vendor";
import { PurchaseOrderService } from "../purchaseOrder.service";

@graphql.Resolver(() => PurchaseOrder)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PurchaseOrderResolverBase {
  constructor(
    protected readonly service: PurchaseOrderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PurchaseOrder",
    action: "read",
    possession: "any",
  })
  async _purchaseOrdersMeta(
    @graphql.Args() args: PurchaseOrderFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [PurchaseOrder])
  @nestAccessControl.UseRoles({
    resource: "PurchaseOrder",
    action: "read",
    possession: "any",
  })
  async purchaseOrders(
    @graphql.Args() args: PurchaseOrderFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PurchaseOrder[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "PurchaseOrder",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => PurchaseOrder, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PurchaseOrder",
    action: "read",
    possession: "own",
  })
  async purchaseOrder(
    @graphql.Args() args: PurchaseOrderFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PurchaseOrder | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "PurchaseOrder",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => PurchaseOrder)
  @nestAccessControl.UseRoles({
    resource: "PurchaseOrder",
    action: "create",
    possession: "any",
  })
  async createPurchaseOrder(
    @graphql.Args() args: CreatePurchaseOrderArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PurchaseOrder> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "PurchaseOrder",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"PurchaseOrder"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        vendor: args.data.vendor
          ? {
              connect: args.data.vendor,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => PurchaseOrder)
  @nestAccessControl.UseRoles({
    resource: "PurchaseOrder",
    action: "update",
    possession: "any",
  })
  async updatePurchaseOrder(
    @graphql.Args() args: UpdatePurchaseOrderArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PurchaseOrder | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "PurchaseOrder",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"PurchaseOrder"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          vendor: args.data.vendor
            ? {
                connect: args.data.vendor,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PurchaseOrder)
  @nestAccessControl.UseRoles({
    resource: "PurchaseOrder",
    action: "delete",
    possession: "any",
  })
  async deletePurchaseOrder(
    @graphql.Args() args: DeletePurchaseOrderArgs
  ): Promise<PurchaseOrder | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [PurchaseOrderItem])
  @nestAccessControl.UseRoles({
    resource: "PurchaseOrder",
    action: "read",
    possession: "any",
  })
  async purchaseOrder(
    @graphql.Parent() parent: PurchaseOrder,
    @graphql.Args() args: PurchaseOrderItemFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PurchaseOrderItem[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "PurchaseOrderItem",
    });
    const results = await this.service.findPurchaseOrder(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => Vendor, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PurchaseOrder",
    action: "read",
    possession: "any",
  })
  async vendor(
    @graphql.Parent() parent: PurchaseOrder,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Vendor | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Vendor",
    });
    const result = await this.service.getVendor(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
